import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { prisma } from '../server/db/client';
import React from 'react';
import Table from '../components/table/Table';
import { useSession, signIn } from 'next-auth/react';

const Home: NextPage = (contacts) => {
  const { status, data } = useSession();

  console.log('status', status);
  console.log('data', data);

  const handleSubmit = async () => {
    const response = await axios.post('/api/predict/addPrediction', {
      data: {
        assetId: '1',
        userId: data?.user!.id,
      },
    });
    console.log('response', response);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>

        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={handleSubmit}>click me</button>
      </div>
      {/* <Table /> */}
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const contacts = await prisma.contact.findMany();

  return {
    props: {
      contacts,
    },
  };
}
