import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { prisma } from '../server/db/client';
import React from 'react';
import Table from '../components/table/Table';

const Home: NextPage = (contacts) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>as</div>
      <Table />
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const contacts = await prisma.contact.findMany();

  return {
    props: {
      contacts,
    },
  };
}
